# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MENU1.UI'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QPushButton,
    QSizePolicy, QSpacerItem, QVBoxLayout, QWidget)

class Ui_menu(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1264, 664)
        Form.setStyleSheet(u"background-color: rgb(170, 0, 0);\n"
"background-color: rgb(171, 171, 171);")
        self.menuLateral = QFrame(Form)
        self.menuLateral.setObjectName(u"menuLateral")
        self.menuLateral.setGeometry(QRect(0, 0, 160, 666))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuLateral.sizePolicy().hasHeightForWidth())
        self.menuLateral.setSizePolicy(sizePolicy)
        self.menuLateral.setMinimumSize(QSize(160, 0))
        self.menuLateral.setMaximumSize(QSize(160, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        brush1 = QBrush(QColor(255, 79, 79, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush1)
        brush2 = QBrush(QColor(239, 39, 39, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush2)
        brush3 = QBrush(QColor(111, 0, 0, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush3)
        brush4 = QBrush(QColor(149, 0, 0, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush4)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        brush6 = QBrush(QColor(239, 127, 127, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush6)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        brush8 = QBrush(QColor(223, 0, 0, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        self.menuLateral.setPalette(palette)
        self.menuLateral.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.menuLateral.setFrameShape(QFrame.StyledPanel)
        self.menuLayout = QVBoxLayout(self.menuLateral)
        self.menuLayout.setSpacing(8)
        self.menuLayout.setObjectName(u"menuLayout")
        self.menuLayout.setContentsMargins(8, 8, 8, 8)
        self.btnInicio = QPushButton(self.menuLateral)
        self.btnInicio.setObjectName(u"btnInicio")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.btnInicio.sizePolicy().hasHeightForWidth())
        self.btnInicio.setSizePolicy(sizePolicy1)
        palette1 = QPalette()
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        brush9 = QBrush(QColor(255, 127, 127, 255))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush9)
        brush10 = QBrush(QColor(255, 63, 63, 255))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush10)
        brush11 = QBrush(QColor(127, 0, 0, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush11)
        brush12 = QBrush(QColor(170, 0, 0, 255))
        brush12.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush12)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush12)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush7)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush9)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush10)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush11)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush12)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush12)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush7)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
        brush13 = QBrush(QColor(122, 122, 122, 255))
        brush13.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush13)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush9)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush10)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush11)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush13)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush13)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush7)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        self.btnInicio.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        font.setBold(True)
        self.btnInicio.setFont(font)
        self.btnInicio.setStyleSheet(u"border-bottom-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(170, 0, 0);\n"
"border-color: rgb(170, 0, 0);")
        icon = QIcon()
        icon.addFile(u"../../../Downloads/\u00edcone-do-vetor-da-casa-ilustra\u00e7\u00e3o-home-preto-e-branco-\u00edcone-linear-cont\u00ednuo-da-casa-para-aplica\u00e7\u00f5es-m\u00f3veis-93005323.webp", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnInicio.setIcon(icon)
        self.btnInicio.setIconSize(QSize(30, 30))
        self.btnInicio.setAutoDefault(False)
        self.btnInicio.setFlat(False)

        self.menuLayout.addWidget(self.btnInicio)

        self.btnConfig = QPushButton(self.menuLateral)
        self.btnConfig.setObjectName(u"btnConfig")
        self.btnConfig.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.btnConfig.sizePolicy().hasHeightForWidth())
        self.btnConfig.setSizePolicy(sizePolicy1)
        self.btnConfig.setMaximumSize(QSize(142, 16777215))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(9)
        font1.setBold(True)
        self.btnConfig.setFont(font1)
        self.btnConfig.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        icon1 = QIcon()
        icon1.addFile(u"../../../Downloads/Designer (9).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnConfig.setIcon(icon1)
        self.btnConfig.setIconSize(QSize(40, 30))
        self.btnConfig.setFlat(False)

        self.menuLayout.addWidget(self.btnConfig)

        self.menuSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.menuLayout.addItem(self.menuSpacer)

        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(170, 0, 1102, 666))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(14)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.btnCadastroAmb = QPushButton(self.layoutWidget)
        self.btnCadastroAmb.setObjectName(u"btnCadastroAmb")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btnCadastroAmb.sizePolicy().hasHeightForWidth())
        self.btnCadastroAmb.setSizePolicy(sizePolicy2)
        self.btnCadastroAmb.setMinimumSize(QSize(250, 150))
        self.btnCadastroAmb.setFont(font)
        self.btnCadastroAmb.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        icon2 = QIcon()
        icon2.addFile(u"../../../Downloads/Designer (5).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnCadastroAmb.setIcon(icon2)
        self.btnCadastroAmb.setIconSize(QSize(128, 128))
        self.btnCadastroAmb.setFlat(False)

        self.gridLayout.addWidget(self.btnCadastroAmb, 0, 0, 1, 1)

        self.btnModificarAmb = QPushButton(self.layoutWidget)
        self.btnModificarAmb.setObjectName(u"btnModificarAmb")
        sizePolicy2.setHeightForWidth(self.btnModificarAmb.sizePolicy().hasHeightForWidth())
        self.btnModificarAmb.setSizePolicy(sizePolicy2)
        self.btnModificarAmb.setMinimumSize(QSize(250, 150))
        self.btnModificarAmb.setFont(font)
        self.btnModificarAmb.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        icon3 = QIcon()
        icon3.addFile(u"../../../Downloads/Designer (6).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnModificarAmb.setIcon(icon3)
        self.btnModificarAmb.setIconSize(QSize(128, 128))

        self.gridLayout.addWidget(self.btnModificarAmb, 0, 1, 1, 1)

        self.btnRelatorio = QPushButton(self.layoutWidget)
        self.btnRelatorio.setObjectName(u"btnRelatorio")
        sizePolicy2.setHeightForWidth(self.btnRelatorio.sizePolicy().hasHeightForWidth())
        self.btnRelatorio.setSizePolicy(sizePolicy2)
        self.btnRelatorio.setMinimumSize(QSize(250, 150))
        self.btnRelatorio.setFont(font)
        self.btnRelatorio.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        icon4 = QIcon()
        icon4.addFile(u"../../../Downloads/Designer (7).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnRelatorio.setIcon(icon4)
        self.btnRelatorio.setIconSize(QSize(128, 128))

        self.gridLayout.addWidget(self.btnRelatorio, 1, 0, 1, 1)

        self.btnInserirDados = QPushButton(self.layoutWidget)
        self.btnInserirDados.setObjectName(u"btnInserirDados")
        sizePolicy2.setHeightForWidth(self.btnInserirDados.sizePolicy().hasHeightForWidth())
        self.btnInserirDados.setSizePolicy(sizePolicy2)
        self.btnInserirDados.setMinimumSize(QSize(250, 150))
        self.btnInserirDados.setFont(font)
        self.btnInserirDados.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        icon5 = QIcon()
        icon5.addFile(u"../../../Downloads/Designer (8).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnInserirDados.setIcon(icon5)
        self.btnInserirDados.setIconSize(QSize(128, 128))

        self.gridLayout.addWidget(self.btnInserirDados, 1, 1, 1, 1)


        self.retranslateUi(Form)

        self.btnInicio.setDefault(False)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.btnInicio.setText(QCoreApplication.translate("Form", u"In\u00edcio", None))
        self.btnConfig.setText(QCoreApplication.translate("Form", u"Ajuste", None))
        self.btnCadastroAmb.setText(QCoreApplication.translate("Form", u"CADASTRO DE AMBUL\u00c2NCIA", None))
        self.btnModificarAmb.setText(QCoreApplication.translate("Form", u"MODIFICAR AMBUL\u00c2NCIA", None))
        self.btnRelatorio.setText(QCoreApplication.translate("Form", u"RELAT\u00d3RIO", None))
        self.btnInserirDados.setText(QCoreApplication.translate("Form", u"INSERIR DADOS", None))
    # retranslateUi

